apiVersion: apps/v1
kind: Deployment
metadata:
  name: KridhaWebApp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: KridhaWebApp
  template:
    metadata:
      labels:
        app: KridhaWebApp
    spec:
      containers:
      - name: KridhaWebApp
        image: <your_account_id>.dkr.ecr.us-west-2.amazonaws.com/my-spring-boot-app:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: KridhaWebApp-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: KridhaWebApp
